export const portfolioData = {
  hero: {
    name: "Iñaki Sobera Sotomayor",
    summary: "Apasionado por la programación, la IA y la ciberseguridad.",
    glitchText: "Iñaki Sobera Sotomayor",
  },
  about: {
    title: "Perfil Profesional",
    bio: [
      "Desarrollador orientado a resultados, con experiencia en programación orientada a objetos y desarrollo backend, adquirida mediante la realización de proyectos personales en entornos Linux. Apasionado por la innovación tecnológica y la resolución de problemas complejos, con capacidad demostrada para transformar ideas en soluciones funcionales y eficientes.",
      "Busco incorporarme a un equipo profesional donde pueda aplicar mis conocimientos técnicos y seguir desarrollándome, con un enfoque claro en el desarrollo backend. Mi objetivo es especializarme en la construcción de sistemas robustos y escalables, en lugar de roles full-stack.",
    ],
    skillsSummary: "Poseo experiencia práctica en un amplio y diverso conjunto de frameworks y librerías de desarrollo. Empleo Spring Boot para diseñar y construir servicios backend escalables en el ecosistema Java, y Flask para el desarrollo rápido de APIs y aplicaciones web con Python. Para aplicaciones de escritorio, tengo conocimientos en JavaFX y CustomTkinter. Además, utilizo herramientas como OpenCV para el procesamiento de imágenes y la ejecución de proyectos de visión por computadora.",
    cvUrl: "cv/cv_inaki_sobera.pdf",
    imageUrl: "yo.png",
  },
  projects: [
    {
      title: "Juego de Supervivencia con IA (Pygame)",
      description: "El proyecto más grande y ambicioso que he realizado: un juego desarrollado en Pygame con monstruos dotados de inteligencia artificial. Los enemigos pueden navegar el mapa de forma autónoma, recolectar ítems y perseguir al jugador para capturarlo.",
      image: "inteligentes.png",
      github: "https://github.com/nanisadw3/Juego_pygame.git",
    },
    {
      title: "Programa de Administración de Rentas con Python y Flask",
      description: "Sistema web para administrar propiedades de alquiler. Centraliza la gestión de propiedades, inquilinos y contratos, automatizando el seguimiento de pagos y reportes. Utiliza PostgreSQL.",
      image: "Rentas.png",
      github: "https://github.com/nanisadw3/Administracion_Rentas",
      demo: "https://app-rentas-df0b56466a50.herokuapp.com/login",
    },
    {
      title: "Página de la NASA con Flask",
      description: "Aplicación web interactiva que consume la API de la NASA para explorar el cosmos (APOD, objetos cercanos, galería). Desarrollada con Python y Flask.",
      image: "api_nasa.png",
      github: "https://github.com/nanisadw3/Nasa",
      demo: "https://fast-caverns-93506-bec36e522de8.herokuapp.com/",
    },
    {
      title: "Pokémon Adivina Quién (Multijugador)",
      description: "Juego multijugador en tiempo real que utiliza la PokeAPI para un desafío de adivinar el Pokémon. Desarrollé tanto el frontend interactivo como el servidor para gestionar las partidas en red.",
      image: "images/pokemon.png",
      github: "https://github.com/nanisadw3/Pokemon_game",
      demo: "https://oyster-app-xwu29.ondigitalocean.app/",
    },
    {
      title: "YOLO Vision",
      description: "Sistema de detección de objetos en tiempo real con YOLO. Procesa video identificando y clasificando objetos. Python con OpenCV.",
      image: "yolo.png",
      github: "https://github.com/nanisadw3/YOLO-Vision.git",
    },
    {
      title: "Sistema de Gestión de Inventario",
      description: "Aplicación de escritorio con GUI intuitiva para el control de productos, categorías y stock. Conexión a base de datos relacional.",
      image: "Sistema_gestion_inventario.png",
      github: "https://github.com/nanisadw3/Sistema-de-Gesti-n-de-Inventario-Python-GUI-con-BD-",
    },
    {
      title: "Java FX",
      description: "Colección de proyectos de escritorio que implementan el patrón MVC. Demuestran habilidades en software modular y escalable.",
      image: "FX.jpg",
      github: "https://github.com/nanisadw3/Practicas_javaFX.git",
    },
    {
      title: "Juego en C#",
      description: "RPG dungeon crawler en C#. Aplica POO para personajes, IA de enemigos y generación procedural de niveles.",
      image: "Juego.jpeg",
      github: "https://github.com/nanisadw3/Calabozo",
    },
    {
      title: "Chat multiusuario con cifrado SSL",
      description: "Chat seguro con CustomTkinter. Utiliza cifrado SSL para proteger comunicaciones en tiempo real entre múltiples usuarios.",
      image: "chat.png",
      github: "https://github.com/nanisadw3/Chat.git",
    },
  ],
  education: [
    {
      title: "Ingeniería en Sistemas Computacionales",
      institution: "UNITEC Campus Atizapán",
      period: "2021 - 2025",
      description: "Estudiante enfocado en desarrollo de software, inteligencia artificial y ciberseguridad.",
    },
    {
      title: "Certificación en Linux",
      institution: "Hack4u.io",
      date: "25/07/2025",
      description: "Gestión avanzada de procesos, redes y configuración de servicios como SSH.",
      certCode: "2154-4957-5308-3366",
      certLink: "cr/inaki_sobera_cr_linux.pdf",
      verifyLink: "https://hack4u.io/check-certificate/",
    },
    {
      title: "Certificación Fundamentos de IA de Oracle",
      institution: "Oracle",
      date: "25/10/2025",
      description: "Conceptos fundamentales de IA y aprendizaje automático en OCI.",
      certLink: "cr/eCertificate.pdf",
      verifyLink: "https://catalog-education.oracle.com/ords/certview/sharebadge?id=6D1FB7CBF3FBA537BBEDA88165A459092AB4323ECAD0D17D0900742075E69B19",
    },
    {
      title: "Certificado en Python Ofensivo",
      institution: "Hack4u.io",
      period: "2024",
      description: "Python aplicado a seguridad ofensiva, herramientas de hacking ético y exploits.",
      certCode: "4240-5530-1286-1447",
      certLink: "cr/inaki_sobera_cr_python.pdf",
      verifyLink: "https://hack4u.io/check-certificate/",
    },
    {
      title: "Certificación en GitHub Foundations",
      institution: "GitHub",
      period: "En proceso",
      description: "Control de versiones, flujos de trabajo colaborativos y herramientas modernas de desarrollo.",
    },
  ],
  skills: {
    programming: ["Java", "Python", "Ruby", "Bash", "C#"],
    frontend: ["HTML5", "CSS3", "JavaScript", "React"],
    tools: ["Git", "GitHub", "Docker", "Linux", "Neovim"],
    databases: ["MySQL", "PostgreSQL", "SQL Server"],
    languages: [
      { name: "Español", level: 100 },
      { name: "Inglés", level: 70 },
    ],
  },
  contact: {
    email: "inakisobera8@gmail.com",
    whatsapp: "+52 5510310275",
    phone: "+52 5510310275",
    github: "https://github.com/nanisadw3",
    linkedin: "https://www.linkedin.com/in/iñaki-sobera-sotomayor-40a87b300/",
    twitter: "https://x.com/InakiSobera",
    web3FormsKey: "7f917ac8-8646-41b5-9450-187a24ad314c",
  },
};
