export const portfolioData = {
  hero: {
    name: "Iñaki Sobera Sotomayor",
    summary: "Ingeniero de Software especializado en el desarrollo de arquitecturas backend robustas, integración estratégica de IA y aseguramiento de infraestructuras críticas.",
    glitchText: "Iñaki Sobera Sotomayor",
  },
  about: {
    title: "Perfil Profesional",
    bio: [
      "Ingeniero enfocado en la entrega de soluciones tecnológicas de alto impacto y la optimización de procesos críticos. Mi trayectoria destaca por la capacidad de transformar desafíos técnicos complejos en sistemas funcionales, escalables y seguros, con un dominio profundo del ecosistema Linux y el desarrollo Backend.",
      "Mi visión se centra en la excelencia técnica y la innovación constante. Busco integrar equipos de ingeniería donde la robustez del código y la integridad de la arquitectura sean los pilares fundamentales, aportando una mentalidad analítica para escalar sistemas empresariales.",
    ],
    skillsSummary: "Experto en el diseño de microservicios con Spring Boot y APIs ágiles con Flask. Sólida experiencia en administración avanzada de Linux, orquestación con Docker y desarrollo de interfaces de control con JavaFX. Especialista en visión artificial mediante OpenCV para automatización industrial.",
    cvUrl: "cv/cv_inaki_sobera.pdf",
    imageUrl: "images/yo.png",
  },
  projects: [
    {
      title: "AI Survival Ecosystem",
      description: "Motor de juego avanzado con agentes autónomos. Implementación de algoritmos de navegación dinámica, gestión de estados complejos y recolección inteligente de recursos en tiempo real.",
      image: "images/inteligentes.png",
      github: "https://github.com/nanisadw3/Juego_pygame.git",
      tags: ["Python", "Neural Logic", "Pygame"],
    },
    {
      title: "BattleNet Pokémon",
      description: "Plataforma multijugador masiva sincronizada mediante sockets. Ingeniería de baja latencia para desafíos competitivos en tiempo real con integración de PokeAPI.",
      image: "images/pokemon.png",
      github: "https://github.com/nanisadw3/Pokemon-Game",
      demo: "https://oyster-app-xwu29.ondigitalocean.app/",
      tags: ["Node.js", "WebSockets", "React"],
    },
    {
      title: "YOLO Kinetic Vision",
      description: "Detección y clasificación de objetos en tiempo real mediante redes neuronales convolucionales. Optimización de procesamiento de video para análisis de alta velocidad.",
      image: "images/yolo.png",
      github: "https://github.com/nanisadw3/YOLO-Vision.git",
      tags: ["OpenCV", "Computer Vision", "Python"],
    },
    {
      title: "Sync Spotify Client",
      description: "Aplicación de escritorio para la gestión inteligente de catálogos musicales. Sincronización automatizada de metadatos mediante integración multicanal con APIs de streaming.",
      image: "images/Spotify.png",
      github: "https://github.com/nanisadw3/Mi-Spotify-.git",
      tags: ["Desktop App", "Spotify API", "Multimedia"],
    },
    {
      title: "Cipher-Stream Chat",
      description: "Sistema de comunicación segura con cifrado extremo a extremo. Implementación de capas de transporte SSL/TLS para garantizar la confidencialidad total de los datos.",
      image: "images/chat.png",
      github: "https://github.com/nanisadw3/Chat.git",
      tags: ["Cybersecurity", "Networking", "Python"],
    },
    {
      title: "Cosmos Telemetry",
      description: "Explorador interactivo de telemetría espacial procesando datos dinámicos de la NASA. Visualización avanzada de objetos celestes y eventos astronómicos.",
      image: "images/api_nasa.png",
      github: "https://github.com/nanisadw3/Nasa",
      demo: "https://fast-caverns-93506-bec36e522de8.herokuapp.com/",
      tags: ["Flask", "Astronomy Data", "Cloud Deploy"],
    },
    {
      title: "Property Management System",
      description: "Software empresarial para administración de activos inmobiliarios. Automatización de flujos financieros y gestión de contratos integrados con PostgreSQL.",
      image: "images/Rentas.png",
      github: "https://github.com/nanisadw3/Administracion_Rentas",
      demo: "https://app-rentas-df0b56466a50.herokuapp.com/login",
      tags: ["Full Stack", "PostgreSQL", "Bussiness Logic"],
    },
    {
      title: "Java FX MVC Architecture",
      description: "Ecosistema de aplicaciones modulares que demuestran el dominio de patrones de diseño empresariales para software escalable.",
      image: "images/FX.jpg",
      github: "https://github.com/nanisadw3/Practicas_javaFX.git",
      tags: ["Java", "MVC Pattern", "OOP"],
    },
    {
      title: "Inventory Intelligence",
      description: "Solución de escritorio para el control de existencias. Interfaz optimizada para la gestión eficiente de almacenes y logística corporativa.",
      image: "images/Sistema_gestion_inventario.png",
      github: "https://github.com/nanisadw3/Sistema-de-Gesti-n-de-Inventario-Python-GUI-con-BD-",
      tags: ["GUI Design", "Python", "Database"],
    },
  ],
  education: [
    {
      title: "Maestría en Dirección de Proyectos",
      institution: "UNITEC Campus Atizapán",
      period: "2026 - En curso",
      description: "Especialización enfocada en metodologías de gestión ágil, control de presupuestos, gestión del alcance y dirección de equipos multidisciplinarios para el éxito de iniciativas tecnológicas.",
    },
    {
      title: "Ingeniería en Sistemas Computacionales",
      institution: "UNITEC Campus Atizapán",
      period: "2023 - 2026",
      description: "Graduado con formación de alto nivel enfocada en el ciclo de vida del software, IA aplicada y ciberseguridad avanzada.",
    },
    {
      title: "Advanced Linux Systems Administration",
      institution: "Hack4u.io",
      date: "25/07/2025",
      description: "Dominio en gestión de procesos críticos, seguridad SSH y administración de infraestructuras Linux.",
      certCode: "2154-4957-5308-3366",
      certLink: "cr/inaki_sobera_cr_linux.pdf",
      verifyLink: "https://hack4u.io/check-certificate/",
    },
    {
      title: "Oracle AI Foundations Certification",
      institution: "Oracle",
      date: "25/10/2025",
      description: "Certificación oficial en pilares de IA y Machine Learning sobre infraestructuras de Oracle Cloud.",
      certLink: "cr/eCertificate.pdf",
      verifyLink: "https://catalog-education.oracle.com/ords/certview/sharebadge?id=6D1FB7CBF3FBA537BBEDA88165A459092AB4323ECAD0D17D0900742075E69B19",
    },
    {
      title: "Offensive Python Specialist",
      institution: "Hack4u.io",
      period: "2024",
      description: "Especialización en herramientas de seguridad ofensiva y protocolos de hacking ético mediante Python.",
      certCode: "4240-5530-1286-1447",
      certLink: "cr/inaki_sobera_cr_python.pdf",
      verifyLink: "https://hack4u.io/check-certificate/",
    },
    {
      title: "GitHub Foundations Certification",
      institution: "GitHub",
      date: "2026",
      description: "Certificación oficial en administración de repositorios, flujos de trabajo colaborativos y control de versiones profesional con Git y GitHub.",
    },
  ],
  experience: [
    {
      role: "Analista en Tecnologías de Operación",
      company: "PEMEX",
      period: "Mayo 2026 - Presente",
      description: "Liderazgo técnico en la automatización de procesos operativos y analítica avanzada para tecnologías de operación.",
      highlights: [
        "Inteligencia Artificial y Automatización: Establecí flujos de notificación autónomos integrando modelos de IA locales con servidores de correo, implementando pipelines de orquestación en n8n.",
        "Análisis de Datos (BI): Optimicé la visibilidad de métricas operativas al consolidar múltiples fuentes de datos en tiempo real mediante la construcción de dashboards interactivos en Power BI.",
        "Desarrollo Backend: Reduje significativamente la captura manual de información departamental desarrollando y desplegando scripts personalizados en Python."
      ],
      tags: ["AI Integration", "n8n Pipelines", "Power BI", "Python Scripting"]
    }
  ],
  skills: {
    programming: ["Java", "Python", "Ruby", "Bash", "C#"],
    frontend: ["Next.js", "React", "TypeScript", "Tailwind CSS"],
    tools: ["Linux Admin", "Git/GitHub", "Docker", "CI/CD", "Neovim", "Power BI"],
    databases: ["PostgreSQL", "MySQL", "SQL Server", "Redis"],
    languages: [
      { name: "Español", level: 100 },
      { name: "Inglés", level: 75 },
    ],
  },
  contact: {
    email: "inakisobera8@gmail.com",
    whatsapp: "+52 5510310275",
    phone: "+52 5510310275",
    github: "https://github.com/nanisadw3",
    linkedin: "https://www.linkedin.com/in/iñaki-sobera-sotomayor-40a87b300/",
    twitter: "https://x.com/InakiSobera",
    web3FormsKey: "7f917ac8-8646-41b5-9450-187a24ad314c",
  },
};
