export const portfolioDataEs = {
  hero: {
    name: "Iñaki Sobera Sotomayor",
    summary: "Ingeniero de Software especializado en el desarrollo de arquitecturas backend robustas, integración estratégica de IA y aseguramiento de infraestructuras críticas.",
    glitchText: "Iñaki Sobera Sotomayor",
  },
  about: {
    title: "Perfil Profesional",
    bio: [
      "Ingeniero enfocado en la entrega de soluciones tecnológicas de alto impacto y la optimización de procesos críticos. Mi trayectoria destaca por la capacidad de transformar desafíos técnicos complejos en sistemas funcionales, escalables y seguros, con un dominio profundo del ecosistema Linux y el desarrollo Backend.",
      "Mi visión se centra en la excelencia técnica y la innovación constante. Busco integrar equipos de ingeniería donde la robustez del código y la integridad de la arquitectura sean los pilares fundamentales, aportando una mentalidad analítica para escalar sistemas empresariales.",
    ],
    skillsSummary: "Experto en el diseño de microservicios con Spring Boot y APIs ágiles con Flask. Sólida experiencia en administración avanzada de Linux, orquestación con Docker y desarrollo de interfaces de control con JavaFX. Especialista en visión artificial mediante OpenCV para automatización industrial.",
    cvUrl: "cv/cv_inaki_sobera.pdf",
    imageUrl: "images/yo.png",
  },
  projects: [
    {
      title: "MCP Relational AI Gateway",
      description: "Portal de análisis y administración de bases de datos relacionales potenciado por Google Gemini bajo el estándar Model Context Protocol (MCP). Consulta tus bases de datos con lenguaje natural, gráficos dinámicos con zoom interactivo y tema Material Design 3.",
      image: "images/MCP.png",
      github: "https://github.com/nanisadw3/MCP-Relational-AI-Gateway.git",
      tags: ["Flask", "Google Gemini", "SQL Server"],
    },
    {
      title: "YOLO Kinetic Vision",
      description: "Detección y clasificación de objetos en tiempo real mediante redes neuronales convolucionales. Optimización de procesamiento de video para análisis de alta velocidad.",
      image: "images/yolo.png",
      github: "https://github.com/nanisadw3/YOLO-Vision.git",
      tags: ["OpenCV", "Computer Vision", "Python"],
    },
    {
      title: "AI Survival Ecosystem",
      description: "Motor de juego avanzado con agentes autónomos. Implementación de algoritmos de navegación dinámica, gestión de estados complejos y recolección inteligente de recursos en tiempo real.",
      image: "images/inteligentes.png",
      github: "https://github.com/nanisadw3/Juego_pygame.git",
      tags: ["Python", "Neural Logic", "Pygame"],
    },
    {
      title: "BattleNet Pokémon",
      description: "Plataforma multijugador masiva sincronizada mediante sockets. Ingeniería de baja latencia para desafíos competitivos en tiempo real con integración de PokeAPI.",
      image: "images/pokemon.png",
      github: "https://github.com/nanisadw3/Pokemon-Game",
      demo: "https://oyster-app-xwu29.ondigitalocean.app/",
      tags: ["Node.js", "WebSockets", "React"],
    },
    {
      title: "Property Management System",
      description: "Software empresarial para administración de activos inmobiliarios. Automatización de flujos financieros y gestión de contratos integrados con PostgreSQL.",
      image: "images/Rentas.png",
      github: "https://github.com/nanisadw3/Administracion_Rentas",
      demo: "https://app-rentas-df0b56466a50.herokuapp.com/login",
      tags: ["Full Stack", "PostgreSQL", "Bussiness Logic"],
    },
    {
      title: "Cipher-Stream Chat",
      description: "Sistema de comunicación segura con cifrado extremo a extremo. Implementación de capas de transporte SSL/TLS para garantizar la confidencialidad total de los datos.",
      image: "images/chat.png",
      github: "https://github.com/nanisadw3/Chat.git",
      tags: ["Cybersecurity", "Networking", "Python"],
    },
    {
      title: "Cosmos Telemetry",
      description: "Explorador interactivo de telemetría espacial procesando datos dinámicos de la NASA. Visualización avanzada de objetos celestes y eventos astronómicos.",
      image: "images/api_nasa.png",
      github: "https://github.com/nanisadw3/Nasa",
      demo: "https://inaki-vpn.asuscomm.com:8070/",
      tags: ["Flask", "Astronomy Data", "Cloud Deploy"],
    },
    {
      title: "Sync Spotify Client",
      description: "Aplicación de escritorio para la gestión inteligente de catálogos musicales. Sincronización automatizada de metadatos mediante integración multicanal con APIs de streaming.",
      image: "images/Spotify.png",
      github: "https://github.com/nanisadw3/Mi-Spotify-.git",
      tags: ["Desktop App", "Spotify API", "Multimedia"],
    },
    {
      title: "Java FX MVC Architecture",
      description: "Ecosistema de aplicaciones modulares que demuestran el dominio de patrones de diseño empresariales para software escalable.",
      image: "images/FX.jpg",
      github: "https://github.com/nanisadw3/Practicas_javaFX.git",
      tags: ["Java", "MVC Pattern", "OOP"],
    },
  ],
  education: [
    {
      title: "Maestría en Dirección de Proyectos",
      institution: "UNITEC Campus Atizapán",
      period: "2026 - En curso",
      description: "Especialización enfocada en metodologías de gestión ágil, control de presupuestos, gestión del alcance y dirección de equipos multidisciplinarios para el éxito de iniciativas tecnológicas.",
    },
    {
      title: "Ingeniería en Sistemas Computacionales",
      institution: "UNITEC Campus Atizapán",
      period: "2023 - 2026",
      description: "Graduado con formación de alto nivel enfocada en el ciclo de vida del software, IA aplicada y ciberseguridad avanzada.",
    },
    {
      title: "Advanced Linux Systems Administration",
      institution: "Hack4u.io",
      date: "25/07/2025",
      description: "Dominio en gestión de procesos críticos, seguridad SSH y administración de infraestructuras Linux.",
      certCode: "2154-4957-5308-3366",
      certLink: "cr/inaki_sobera_cr_linux.pdf",
      verifyLink: "https://hack4u.io/check-certificate/",
    },
    {
      title: "Oracle AI Foundations Certification",
      institution: "Oracle",
      date: "25/10/2025",
      description: "Certificación oficial en pilares de IA y Machine Learning sobre infraestructuras de Oracle Cloud.",
      certLink: "cr/eCertificate.pdf",
      verifyLink: "https://catalog-education.oracle.com/ords/certview/sharebadge?id=6D1FB7CBF3FBA537BBEDA88165A459092AB4323ECAD0D17D0900742075E69B19",
    },
    {
      title: "Offensive Python Specialist",
      institution: "Hack4u.io",
      period: "2024",
      description: "Especialización en herramientas de seguridad ofensiva y protocolos de hacking ético mediante Python.",
      certCode: "4240-5530-1286-1447",
      certLink: "cr/inaki_sobera_cr_python.pdf",
      verifyLink: "https://hack4u.io/check-certificate/",
    },
    {
      title: "GitHub Foundations Certification",
      institution: "GitHub",
      date: "2026",
      description: "Certificación oficial en administración de repositorios, flujos de trabajo colaborativos y control de versiones profesional con Git y GitHub.",
    },
  ],
  experience: [
    {
      role: "Analista en Tecnologías de Operación",
      company: "PEMEX",
      encrypted: true,
      period: "Mayo 2026 - Presente",
      description: "Liderazgo técnico en la automatización de procesos operativos y analítica avanzada para tecnologías de operación.",
      highlights: [
        "Inteligencia Artificial y Automatización: Establecí flujos de notificación autónomos integrando modelos de IA locales con servidores de correo, implementando pipelines de orquestación en n8n.",
        "Análisis de Datos (BI): Optimicé la visibilidad de métricas operativas al consolidar múltiples fuentes de datos en tiempo real mediante la construcción de dashboards interactivos en Power BI.",
        "Desarrollo Backend: Reduje significativamente la captura manual de información departamental desarrollando y desplegando scripts personalizados en Python."
      ],
      tags: ["AI Integration", "n8n Pipelines", "Power BI", "Python Scripting"]
    }
  ],
  skills: {
    programming: ["Java", "Python", "Ruby", "Bash", "C#"],
    frontend: ["Next.js", "React", "TypeScript", "Tailwind CSS"],
    tools: ["Linux Admin", "Git/GitHub", "Docker", "CI/CD", "Neovim", "Power BI"],
    databases: ["PostgreSQL", "MySQL", "SQL Server", "Redis"],
    languages: [
      { name: "Español", level: 100 },
      { name: "Inglés", level: 75 },
    ],
  },
  contact: {
    email: "inakisobera8@gmail.com",
    whatsapp: "+52 5510310275",
    phone: "+52 5510310275",
    github: "https://github.com/nanisadw3",
    linkedin: "https://www.linkedin.com/in/iñaki-sobera-sotomayor-40a87b300/",
    twitter: "https://x.com/InakiSobera",
    web3FormsKey: "7f917ac8-8646-41b5-9450-187a24ad314c",
  },
  ui: {
    nav: {
      home: "Inicio",
      profile: "Perfil",
      exp: "Exp.",
      projects: "Proyectos",
      skills: "Especialidad",
      contact: "Contacto",
    },
    hero: {
      projectsBtn: "Proyectos",
    },
    about: {
      biometric: "Biometric Profile",
      verified: "Identity Verified",
      role: "Software Engineer",
      download: "Capture CV",
      systems: "Systems Active",
    },
    experience: {
      badge: "Professional Track",
      title1: "EXPERIENCIA",
      title2: "PROFESIONAL",
      active: "Activo",
      subtitle: "Logros e Impacto Operativo",
    },
    portfolio: {
      badge: "Works & Labs",
      title1: "PROYECTOS",
      title2: "DESTACADOS",
      archiveBtn: "GitHub Archive",
      activeSystem: "Active System",
      viewArchive: "Ver Archivo",
      collapse: "Colapsar Archivo",
      expand: "Desplegar Laboratorio",
    },
    skills: {
      badge: "Capabilities",
      title1: "TECHNICAL",
      title2: "MASTERY",
      desc: "Un stack tecnológico diseñado para la eficiencia, la seguridad y la escalabilidad.",
      languages: "Global Communication",
      verified: "Verified Professional Stack",
    },
    education: {
      badge: "Academic & Certs",
      title1: "TRAINING &",
      title2: "CREDENTIALS",
      validated: "Validado",
      verify: "Verify Badge",
      location: "Remote / Global",
    },
    stats: {
      title: "GitHub Insights",
      contributions: "Calendario de Contribuciones",
      streak: "Racha de Código",
      streakDesc: "Días consecutivos de actividad y compromiso.",
      followers: "Seguidores",
      since: "En GitHub desde",
      activity: "Última Actividad",
      following: "Siguiendo",
    },
    contact: {
      badge: "Connection: Active",
      title1: "LET'S",
      title2: "SYNC.",
      desc: "Iniciemos una conversación sobre sistemas o arquitectura. El canal está abierto.",
      identity: "Identidad",
      source: "Fuente de la Señal (Email)",
      payload: "Carga Útil (Mensaje)",
      send: "Enviar Transmisión",
      rights: "TODOS LOS DERECHOS RESERVADOS",
      design: "Diseño & Dev por Sobera Labs",
    },
  },
};

export const portfolioDataEn = {
  hero: {
    name: "Iñaki Sobera Sotomayor",
    summary: "Software Engineer specialized in developing robust backend architectures, strategic AI integration, and securing critical infrastructures.",
    glitchText: "Iñaki Sobera Sotomayor",
  },
  about: {
    title: "Professional Profile",
    bio: [
      "Engineer focused on delivering high-impact technological solutions and optimizing critical processes. My career is defined by the ability to transform complex technical challenges into functional, scalable, and secure systems, with deep expertise in the Linux ecosystem and Backend development.",
      "My vision is centered on technical excellence and constant innovation. I seek to join engineering teams where code robustness and architectural integrity are fundamental pillars, bringing an analytical mindset to scale enterprise systems.",
    ],
    skillsSummary: "Expert in microservices design with Spring Boot and agile APIs with Flask. Solid experience in advanced Linux administration, orchestration with Docker, and control interface development with JavaFX. Specialist in computer vision using OpenCV for industrial automation.",
    cvUrl: "cv/cv_inaki_sobera.pdf",
    imageUrl: "images/yo.png",
  },
  projects: [
    {
      title: "MCP Relational AI Gateway",
      description: "Relational database analysis and administration portal powered by Google Gemini under the Model Context Protocol (MCP) standard. Query your databases in natural language, with dynamic interactive-zoom charts and a Material Design 3 theme.",
      image: "images/MCP.png",
      github: "https://github.com/nanisadw3/MCP-Relational-AI-Gateway.git",
      tags: ["Flask", "Google Gemini", "SQL Server"],
    },
    {
      title: "YOLO Kinetic Vision",
      description: "Real-time object detection and classification using convolutional neural networks. Video processing optimization for high-speed analysis.",
      image: "images/yolo.png",
      github: "https://github.com/nanisadw3/YOLO-Vision.git",
      tags: ["OpenCV", "Computer Vision", "Python"],
    },
    {
      title: "AI Survival Ecosystem",
      description: "Advanced game engine with autonomous agents. Implementation of dynamic navigation algorithms, complex state management, and real-time intelligent resource gathering.",
      image: "images/inteligentes.png",
      github: "https://github.com/nanisadw3/Juego_pygame.git",
      tags: ["Python", "Neural Logic", "Pygame"],
    },
    {
      title: "BattleNet Pokémon",
      description: "Massive multiplayer platform synchronized via sockets. Low-latency engineering for real-time competitive challenges with PokeAPI integration.",
      image: "images/pokemon.png",
      github: "https://github.com/nanisadw3/Pokemon-Game",
      demo: "https://oyster-app-xwu29.ondigitalocean.app/",
      tags: ["Node.js", "WebSockets", "React"],
    },
    {
      title: "Property Management System",
      description: "Enterprise software for real estate asset management. Automation of financial flows and contract management integrated with PostgreSQL.",
      image: "images/Rentas.png",
      github: "https://github.com/nanisadw3/Administracion_Rentas",
      demo: "https://app-rentas-df0b56466a50.herokuapp.com/login",
      tags: ["Full Stack", "PostgreSQL", "Bussiness Logic"],
    },
    {
      title: "Cipher-Stream Chat",
      description: "Secure communication system with end-to-end encryption. Implementation of SSL/TLS transport layers to guarantee total data confidentiality.",
      image: "images/chat.png",
      github: "https://github.com/nanisadw3/Chat.git",
      tags: ["Cybersecurity", "Networking", "Python"],
    },
    {
      title: "Cosmos Telemetry",
      description: "Interactive space telemetry explorer processing dynamic NASA data. Advanced visualization of celestial objects and astronomical events.",
      image: "images/api_nasa.png",
      github: "https://github.com/nanisadw3/Nasa",
      demo: "https://inaki-vpn.asuscomm.com:8070/",
      tags: ["Flask", "Astronomy Data", "Cloud Deploy"],
    },
    {
      title: "Sync Spotify Client",
      description: "Desktop application for intelligent music catalog management. Automated metadata synchronization via multi-channel streaming API integration.",
      image: "images/Spotify.png",
      github: "https://github.com/nanisadw3/Mi-Spotify-.git",
      tags: ["Desktop App", "Spotify API", "Multimedia"],
    },
    {
      title: "Java FX MVC Architecture",
      description: "Ecosystem of modular applications demonstrating mastery of enterprise design patterns for scalable software.",
      image: "images/FX.jpg",
      github: "https://github.com/nanisadw3/Practicas_javaFX.git",
      tags: ["Java", "MVC Pattern", "OOP"],
    },
  ],
  education: [
    {
      title: "Master's Degree in Project Management",
      institution: "UNITEC Campus Atizapán",
      period: "2026 - In progress",
      description: "Specialization focused on agile management methodologies, budget control, scope management, and leading multidisciplinary teams for the success of technological initiatives.",
    },
    {
      title: "Computer Systems Engineering",
      institution: "UNITEC Campus Atizapán",
      period: "2023 - 2026",
      description: "Graduate with high-level training focused on the software lifecycle, applied AI, and advanced cybersecurity.",
    },
    {
      title: "Advanced Linux Systems Administration",
      institution: "Hack4u.io",
      date: "25/07/2025",
      description: "Mastery in critical process management, SSH security, and Linux infrastructure administration.",
      certCode: "2154-4957-5308-3366",
      certLink: "cr/inaki_sobera_cr_linux.pdf",
      verifyLink: "https://hack4u.io/check-certificate/",
    },
    {
      title: "Oracle AI Foundations Certification",
      institution: "Oracle",
      date: "25/10/2025",
      description: "Official certification in AI and Machine Learning foundations on Oracle Cloud Infrastructure.",
      certLink: "cr/eCertificate.pdf",
      verifyLink: "https://catalog-education.oracle.com/ords/certview/sharebadge?id=6D1FB7CBF3FBA537BBEDA88165A459092AB4323ECAD0D17D0900742075E69B19",
    },
    {
      title: "Offensive Python Specialist",
      institution: "Hack4u.io",
      period: "2024",
      description: "Specialization in offensive security tools and ethical hacking protocols using Python.",
      certCode: "4240-5530-1286-1447",
      certLink: "cr/inaki_sobera_cr_python.pdf",
      verifyLink: "https://hack4u.io/check-certificate/",
    },
    {
      title: "GitHub Foundations Certification",
      institution: "GitHub",
      date: "2026",
      description: "Official certification in repository administration, collaborative workflows, and professional version control with Git and GitHub.",
    },
  ],
  experience: [
    {
      role: "Operations Technology Analyst",
      company: "PEMEX",
      encrypted: true,
      period: "May 2026 - Present",
      description: "Technical leadership in operational process automation and advanced analytics for operations technology.",
      highlights: [
        "Artificial Intelligence and Automation: Established autonomous notification flows integrating local AI models with mail servers, implementing orchestration pipelines in n8n.",
        "Data Analysis (BI): Optimized visibility of operational metrics by consolidating multiple real-time data sources through interactive dashboards in Power BI.",
        "Backend Development: Significantly reduced manual departmental data capture by developing and deploying custom Python scripts."
      ],
      tags: ["AI Integration", "n8n Pipelines", "Power BI", "Python Scripting"]
    }
  ],
  skills: {
    programming: ["Java", "Python", "Ruby", "Bash", "C#"],
    frontend: ["Next.js", "React", "TypeScript", "Tailwind CSS"],
    tools: ["Linux Admin", "Git/GitHub", "Docker", "CI/CD", "Neovim", "Power BI"],
    databases: ["PostgreSQL", "MySQL", "SQL Server", "Redis"],
    languages: [
      { name: "Spanish", level: 100 },
      { name: "English", level: 75 },
    ],
  },
  contact: {
    email: "inakisobera8@gmail.com",
    whatsapp: "+52 5510310275",
    phone: "+52 5510310275",
    github: "https://github.com/nanisadw3",
    linkedin: "https://www.linkedin.com/in/iñaki-sobera-sotomayor-40a87b300/",
    twitter: "https://x.com/InakiSobera",
    web3FormsKey: "7f917ac8-8646-41b5-9450-187a24ad314c",
  },
  ui: {
    nav: {
      home: "Home",
      profile: "Profile",
      exp: "Exp.",
      projects: "Projects",
      skills: "Skills",
      contact: "Contact",
    },
    hero: {
      projectsBtn: "Projects",
    },
    about: {
      biometric: "Biometric Profile",
      verified: "Identity Verified",
      role: "Software Engineer",
      download: "Capture CV",
      systems: "Systems Active",
    },
    experience: {
      badge: "Professional Track",
      title1: "PROFESSIONAL",
      title2: "EXPERIENCE",
      active: "Active",
      subtitle: "Achievements & Operational Impact",
    },
    portfolio: {
      badge: "Works & Labs",
      title1: "FEATURED",
      title2: "PROJECTS",
      archiveBtn: "GitHub Archive",
      activeSystem: "Active System",
      viewArchive: "View Archive",
      collapse: "Collapse Archive",
      expand: "Expand Lab",
    },
    skills: {
      badge: "Capabilities",
      title1: "TECHNICAL",
      title2: "MASTERY",
      desc: "A technological stack designed for efficiency, security, and scalability.",
      languages: "Global Communication",
      verified: "Verified Professional Stack",
    },
    education: {
      badge: "Academic & Certs",
      title1: "TRAINING &",
      title2: "CREDENTIALS",
      validated: "Validated",
      verify: "Verify Badge",
      location: "Remote / Global",
    },
    stats: {
      title: "GitHub Insights",
      contributions: "Contributions Calendar",
      streak: "Coding Streak",
      streakDesc: "Consecutive days of activity and commitment.",
      followers: "Followers",
      since: "On GitHub since",
      activity: "Last Activity",
      following: "Following",
    },
    contact: {
      badge: "Connection: Active",
      title1: "LET'S",
      title2: "SYNC.",
      desc: "Let's start a conversation about systems or architecture. The channel is open.",
      identity: "Identity",
      source: "Signal Source (Email)",
      payload: "Payload Data (Message)",
      send: "Send Transmission",
      rights: "ALL RIGHTS RESERVED",
      design: "Design & Dev by Sobera Labs",
    },
  },
};
