export const portfolioData = {
  hero: {
    name: "Iñaki Sobera Sotomayor",
    summary: "Ingeniero de Software especializado en la arquitectura de sistemas robustos, la integración estratégica de IA y el blindaje de infraestructuras críticas mediante ciberseguridad avanzada.",
    glitchText: "Iñaki Sobera Sotomayor",
    tagline: "Building resilient digital foundations for the future of technology.",
  },
  about: {
    title: "Arquitectura Profesional",
    bio: [
      "Ingeniero en Sistemas enfocado en la entrega de resultados tangibles y soluciones tecnológicas de alto impacto. Mi trayectoria se define por la capacidad de transformar desafíos técnicos complejos en sistemas funcionales, escalables y eficientes, con una especialización profunda en el ecosistema Linux y el desarrollo Backend de alto rendimiento.",
      "Mi visión se centra en la excelencia técnica y la innovación constante. Busco integrar equipos de ingeniería donde la robustez del código y la seguridad de la infraestructura sean los pilares fundamentales, aportando una mentalidad analítica y proactiva para optimizar procesos y escalar arquitecturas críticas.",
    ],
    skillsSummary: "Experto en el diseño y despliegue de microservicios con Spring Boot (Java) y el desarrollo ágil de APIs con Flask (Python). Sólidos conocimientos en la automatización de infraestructuras sobre Linux, orquestación con Docker y el desarrollo de interfaces de control avanzado con JavaFX y CustomTkinter. Especialista en la implementación de visión artificial mediante OpenCV para soluciones de automatización inteligente.",
    cvUrl: "cv/cv_inaki_sobera.pdf",
    imageUrl: "images/yo.png",
  },
  projects: [
    {
      title: "AI Survival Ecosystem (Pygame)",
      description: "Desarrollo de un motor de juego avanzado con agentes autónomos. Implementación de algoritmos de navegación dinámica, gestión de estados complejos para IA y recolección inteligente de recursos en tiempo real.",
      image: "images/inteligentes.png",
      github: "https://github.com/nanisadw3/Juego_pygame.git",
      tags: ["Python", "Pygame", "AI Algorithms"],
    },
    {
      title: "Pokémon Battle-Network (Real-time)",
      description: "Plataforma multijugador masiva sincronizada mediante sockets para desafíos competitivos. Integración fluida con la PokeAPI y gestión de latencia para una experiencia de usuario ininterrumpida.",
      image: "images/pokemon.png",
      github: "https://github.com/nanisadw3/Pokemon-Game",
      demo: "https://oyster-app-xwu29.ondigitalocean.app/",
      tags: ["React", "API Integration", "Socket.io"],
    },
    {
      title: "YOLO Computer Vision",
      description: "Implementación de redes neuronales convolucionales para la detección y clasificación de objetos en tiempo real. Optimización de frames mediante OpenCV para análisis de video de alta velocidad.",
      image: "images/yolo.png",
      github: "https://github.com/nanisadw3/YOLO-Vision.git",
      tags: ["Computer Vision", "Python", "Deep Learning"],
    },
    {
      title: "Sync Spotify Client",
      description: "Aplicación de escritorio para la gestión y descarga inteligente de catálogos musicales. Sincronización automática de metadatos y portadas mediante integración multicanal con APIs de streaming.",
      image: "images/Spotify.png",
      github: "https://github.com/nanisadw3/Mi-Spotify-.git",
      tags: ["Desktop App", "API Spotify", "Multimedia"],
    },
    {
      title: "SSL Encryption Chat",
      description: "Sistema de comunicación segura con arquitectura cliente-servidor. Implementación de capas de transporte cifrado SSL/TLS para garantizar la integridad y confidencialidad total de los datos.",
      image: "images/chat.png",
      github: "https://github.com/nanisadw3/Chat.git",
      tags: ["Cybersecurity", "Networking", "Python"],
    },
    {
      title: "NASA Cosmos Explorer",
      description: "Explorador interactivo del universo que consume el ecosistema de APIs de la NASA. Visualización avanzada de telemetría espacial, objetos cercanos a la tierra y galerías astronómicas dinámicas.",
      image: "images/api_nasa.png",
      github: "https://github.com/nanisadw3/Nasa",
      demo: "https://fast-caverns-93506-bec36e522de8.herokuapp.com/",
      tags: ["Flask", "Astronomy Data", "Cloud Deploy"],
    },
    {
      title: "Property Management System",
      description: "Software de gestión empresarial para la administración de activos inmobiliarios. Automatización de flujos de pago, contratos dinámicos y reportes financieros integrados con PostgreSQL.",
      image: "images/Rentas.png",
      github: "https://github.com/nanisadw3/Administracion_Rentas",
      demo: "https://app-rentas-df0b56466a50.herokuapp.com/login",
      tags: ["Full Stack", "PostgreSQL", "Bussiness Logic"],
    },
    {
      title: "Java FX MVC Practices",
      description: "Ecosistema de aplicaciones modulares que demuestran el dominio del patrón de diseño Modelo-Vista-Controlador. Enfoque en la escalabilidad y mantenibilidad de software empresarial.",
      image: "images/FX.jpg",
      github: "https://github.com/nanisadw3/Practicas_javaFX.git",
      tags: ["Java", "MVC Pattern", "OOP"],
    },
    {
      title: "Smart Inventory Logic",
      description: "Solución de escritorio para el control preciso de existencias y categorías. Interfaz intuitiva diseñada para la optimización de tiempos en la gestión de almacenes y logística.",
      image: "images/Sistema_gestion_inventario.png",
      github: "https://github.com/nanisadw3/Sistema-de-Gesti-n-de-Inventario-Python-GUI-con-BD-",
      tags: ["GUI Design", "Python", "Database"],
    },
  ],
  education: [
    {
      title: "Ingeniería en Sistemas Computacionales",
      institution: "UNITEC Campus Atizapán",
      period: "2021 - 2025",
      description: "Formación de alto nivel enfocada en el ciclo de vida del desarrollo de software, inteligencia artificial aplicada y protocolos críticos de ciberseguridad.",
    },
    {
      title: "Advanced Linux Systems Administration",
      institution: "Hack4u.io",
      date: "25/07/2025",
      description: "Dominio absoluto en la gestión de procesos críticos, topologías de red avanzadas y securización de servicios SSH.",
      certCode: "2154-4957-5308-3366",
      certLink: "cr/inaki_sobera_cr_linux.pdf",
      verifyLink: "https://hack4u.io/check-certificate/",
    },
    {
      title: "Oracle AI Foundations Certification",
      institution: "Oracle",
      date: "25/10/2025",
      description: "Certificación oficial en los pilares fundamentales de la Inteligencia Artificial y Machine Learning sobre infraestructuras de Oracle Cloud (OCI).",
      certLink: "cr/eCertificate.pdf",
      verifyLink: "https://catalog-education.oracle.com/ords/certview/sharebadge?id=6D1FB7CBF3FBA537BBEDA88165A459092AB4323ECAD0D17D0900742075E69B19",
    },
    {
      title: "Offensive Python Specialist",
      institution: "Hack4u.io",
      period: "2024",
      description: "Especialización en la creación de herramientas de seguridad ofensiva, desarrollo de exploits y protocolos de hacking ético mediante Python.",
      certCode: "4240-5530-1286-1447",
      certLink: "cr/inaki_sobera_cr_python.pdf",
      verifyLink: "https://hack4u.io/check-certificate/",
    },
    {
      title: "GitHub Foundations (Certified)",
      institution: "GitHub",
      period: "2026",
      description: "Experto en control de versiones avanzado, flujos de trabajo CI/CD y gestión de ecosistemas de desarrollo colaborativo.",
    },
  ],
  skills: {
    programming: ["Java", "Python", "Ruby", "Bash", "C#"],
    frontend: ["Next.js", "React", "TypeScript", "Tailwind CSS"],
    tools: ["Linux Admin", "Git/GitHub", "Docker", "DevOps Ops", "Neovim"],
    databases: ["PostgreSQL", "MySQL", "SQL Server", "Redis"],
    languages: [
      { name: "Español", level: 100 },
      { name: "Inglés", level: 75 },
    ],
  },
  contact: {
    email: "inakisobera8@gmail.com",
    whatsapp: "+52 5510310275",
    phone: "+52 5510310275",
    github: "https://github.com/nanisadw3",
    linkedin: "https://www.linkedin.com/in/iñaki-sobera-sotomayor-40a87b300/",
    twitter: "https://x.com/InakiSobera",
    web3FormsKey: "7f917ac8-8646-41b5-9450-187a24ad314c",
  },
};
